/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to one of `_getb67', `GETB67', `getb67' for Cray-2 and Cray-YMP
   systems. This function is required for `alloca.c' support on those systems.
   */
/* #undef CRAY_STACKSEG_END */

/* Define to 1 if using `alloca.c'. */
/* #undef C_ALLOCA */

/* Define to 1 if you have `alloca', as a function or macro. */
#define HAVE_ALLOCA 1

/* Define to 1 if you have <alloca.h> and it should be used (not on Ultrix).
   */
#define HAVE_ALLOCA_H 1

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_DIRENT_H */

/* Define to 1 if you have the <dlfcn.h> header file. */
/* #undef HAVE_DLFCN_H */

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the `getpagesize' function. */
/* #undef HAVE_GETPAGESIZE */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <math.h> header file. */
#define HAVE_MATH_H 1

/* Define to 1 if you have the <memory.h> header file. */
/* #undef HAVE_MEMORY_H */

/* Define to 1 if you have a working `mmap' system call. */
/* #undef HAVE_MMAP */

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the `setenv' function. */
/* #undef HAVE_SETENV */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcasecmp' function. */
/* #undef HAVE_STRCASECMP */

/* Define to 1 if you have the `strdup' function. */
/* #undef HAVE_STRDUP */

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
/* #undef HAVE_STRINGS_H */

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
/* #undef HAVE_SYS_STAT_H */

/* Define to 1 if you have the <sys/time.h> header file. */
/* #undef HAVE_SYS_TIME_H */

/* Define to 1 if you have the <sys/types.h> header file. */
/* #undef HAVE_SYS_TYPES_H */

/* Define to 1 if you have the <termio.h> header file. */
/* #undef HAVE_TERMIO_H */

/* Define to 1 if you have the `tmpfile' function. */
#define HAVE_TMPFILE 1

/* Define to 1 if you have the <unistd.h> header file. */
/* #undef HAVE_UNISTD_H */

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Binary age of MiniGUI */
#define MINIGUI_BINARY_AGE 0

/* Interface age of MiniGUI */
#define MINIGUI_INTERFACE_AGE 0

/* Major version of MiniGUI */
#define MINIGUI_MAJOR_VERSION 1

/* Micro version of MiniGUI */
#define MINIGUI_MICRO_VERSION 2

/* Minor version of MiniGUI */
#define MINIGUI_MINOR_VERSION 5

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* If using the C implementation of alloca, define if you know the
   direction of stack growth for your system; otherwise it will be
   automatically deduced at run-time.
        STACK_DIRECTION > 0 => grows toward higher addresses
        STACK_DIRECTION < 0 => grows toward lower addresses
        STACK_DIRECTION = 0 => direction of growth unknown */
/* #undef STACK_DIRECTION */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
/* #undef TIME_WITH_SYS_TIME */

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
#define TM_IN_SYS_TIME 1

/* Define if include input engine for ADS */
/* #undef _ADS_IAL */

/* Define if include advanced 2D graphics APIs */
/* #undef _ADV_2DAPI */

/* Define if support Arabic charset */
/* #undef _ARABIC_SUPPORT */

/* Define if include the automatic IAL engine */
#define _AUTO_IAL 1

/* Define if support BIG5 charset */
/* #undef _BIG5_SUPPORT */

/* Define if include clipboard support */
#define _CLIPBOARD_SUPPORT 1

/* Define if use coordinate transformation */
/* #undef _COOR_TRANS */

/* Define if include BUTTON control */
#define _CTRL_BUTTON 1

/* Define if include COMBOBOX control */
#define _CTRL_COMBOBOX 1

/* Define if include LISTBOX control */
#define _CTRL_LISTBOX 1

/* Define if include MENUBUTTON control */
#define _CTRL_MENUBUTTON 1

/* Define if include MLEDIT control */
#define _CTRL_MLEDIT 1

/* Define if include NEWTOOLBAR control */
#define _CTRL_NEWTOOLBAR 1

/* Define if include PROGRESSBAR control */
#define _CTRL_PROGRESSBAR 1

/* Define if include PROPSHEET control */
#define _CTRL_PROPSHEET 1

/* Define if include SIMEDIT control */
#define _CTRL_SIMEDIT 1

/* Define if include SLEDIT control */
#define _CTRL_SLEDIT 1

/* Define if include STATIC control */
#define _CTRL_STATIC 1

/* Define if include TOOLBAR control */
#define _CTRL_TOOLBAR 1

/* Define if include TRACKBAR control */
#define _CTRL_TRACKBAR 1

/* Define if include cursor support */
/* #undef _CURSOR_SUPPORT */

/* Define if support Cyrillic charset */
/* #undef _CYRILLIC_SUPPORT */

/* Define if include IAL engine for Intel DMG STB Remote Controller */
/* #undef _DMGSTB_IAL */

/* Define if mouse button can do double click */
#define _DOUBLE_CLICK 1

/* Define if include the dummy IAL engine */
#define _DUMMY_IAL 1

/* Define if include input engine for EP7211 */
/* #undef _EP7211_IAL */

/* Define if support EUCJP charset */
/* #undef _EUCJP_SUPPORT */

/* Define if support EUCKR charset */
/* #undef _EUCKR_SUPPORT */

/* Define if include COOLBAR control */
#define _EXT_CTRL_COOLBAR 1

/* Define if include GRID control */
#define _EXT_CTRL_GRID 1

/* Define if include LISTVIEW control */
#define _EXT_CTRL_LISTVIEW 1

/* Define if include MONTHCALENDAR control */
#define _EXT_CTRL_MONTHCAL 1

/* Define if include SPINBOX control */
#define _EXT_CTRL_SPINBOX 1

/* Define if include TREEVIEW control */
#define _EXT_CTRL_TREEVIEW 1

/* Define if include full gif support */
/* #undef _EXT_FULLGIF */

/* Define if include skin support */
#define _EXT_SKIN 1

/* Define if include 4 button state support */
#define _EXT_SKIN_4BTNSTATE 1

/* Define if include 16BPP FB subdriver */
/* #undef _FBLIN16_SUPPORT */

/* Define if include 1BPP FB subdriver (MSB is left) */
/* #undef _FBLIN1L_SUPPORT */

/* Define if include 1BPP FB subdriver (MSB is right) */
/* #undef _FBLIN1R_SUPPORT */

/* Define if include 24BPP FB subdriver */
/* #undef _FBLIN24_SUPPORT */

/* Define if include 2BPP FB subdriver (MSB is left) */
/* #undef _FBLIN2L_SUPPORT */

/* Define if include 2BPP FB subdriver (MSB is right) */
/* #undef _FBLIN2R_SUPPORT */

/* Define if include 32BPP FB subdriver */
/* #undef _FBLIN32_SUPPORT */

/* Define if include 4BPP FB subdriver (MSB is left) */
/* #undef _FBLIN4L_SUPPORT */

/* Define if include 4BPP FB subdriver (MSB is right) */
/* #undef _FBLIN4R_SUPPORT */

/* Define if include 8BPP FB subdriver */
/* #undef _FBLIN8_SUPPORT */

/* Define if include VGA16 FB subdriver */
/* #undef _FBVGA16_SUPPORT */

/* Define if include IAL engine for EM85xx Front Panel and Remote Controller
   */
/* #undef _FIP_IAL */

/* Define if include fixed math routines */
#define _FIXED_MATH 1

/* Define if window style is flat */
/* #undef _FLAT_WINDOW_STYLE */

/* Define if support GB18030 charset */
/* #undef _GB18030_SUPPORT */

/* Define if support GBK charset */
/* #undef _GBK_SUPPORT */

/* Define if support GB2312 charset */
#define _GB_SUPPORT 1

/* Define if support GIF bmp file format */
#define _GIF_FILE_SUPPORT 1

/* Define if include GPM mouse subdriver */
#define _GPM_SUPPORT 1

/* Define if is gray screen */
/* #undef _GRAY_SCREEN */

/* Define if support Greek charset */
/* #undef _GREEK_SUPPORT */

/* Define if has FreeType 2 */
/* #undef _HAS_FREETYPE2 */

/* Define if have math library */
/* #undef _HAVE_MATH_LIB */

/* Define if your Linux have text mode */
#define _HAVE_TEXT_MODE 1

/* Define if support Hebrew charset */
/* #undef _HEBREW_SUPPORT */

/* Define if include IAL engine for Helio Touch Panel */
/* #undef _HELIO_IAL */

/* Define if include GB2312 IME */
/* #undef _IME_GB2312 */

/* Define if include GB2312 Intelligent Pinyin IME module */
/* #undef _IME_GB2312_PINYIN */

/* Define if include IMPS2 mouse subdriver */
#define _IMPS2_SUPPORT 1

/* Define if include in-core font: Courier */
#define _INCOREFONT_COURIER 1

/* Define if include in-core font: SansSerif */
#define _INCOREFONT_SANSSERIF 1

/* Define if include in-core font: Symbol */
#define _INCOREFONT_SYMBOL 1

/* Define if include in-core font: VGAS */
#define _INCOREFONT_VGAS 1

/* Define if include in-core font: 12x12 RBF for GB2312 */
#define _INCORERBF_GB12 1

/* Define if include in-core font: 8x16 RBF for ISO8859-1 */
/* #undef _INCORERBF_LATIN1_16 */

/* Define if include in-core font: 12x24 RBF for ISO8859-1 */
/* #undef _INCORERBF_LATIN1_24 */

/* Define if build MiniGUI for no file I/O system */
#define _INCORE_RES 1

/* Define if include input engine for iPAQ */
/* #undef _IPAQ_IAL */

/* Define if support JPEG bmp file format */
/* #undef _JPG_FILE_SUPPORT */

/* Define if use the German keyboard layout */
/* #undef _KBD_LAYOUT_DE */

/* Define if use the German-Latin1 keyboard layout */
/* #undef _KBD_LAYOUT_DELATIN1 */

/* Define if use the Spanish keyboard layout */
/* #undef _KBD_LAYOUT_ES */

/* Define if use the Spanish CP850 keyboard layout */
/* #undef _KBD_LAYOUT_ESCP850 */

/* Define if use the French keyboard layout */
/* #undef _KBD_LAYOUT_FR */

/* Define if use the French PC keyboard layout */
/* #undef _KBD_LAYOUT_FRPC */

/* Define if use the Italian keyboard layout */
/* #undef _KBD_LAYOUT_IT */

/* Define if support Latin 10 charset */
/* #undef _LATIN10_SUPPORT */

/* Define if support Latin 2 charset */
/* #undef _LATIN2_SUPPORT */

/* Define if support Latin 3 charset */
/* #undef _LATIN3_SUPPORT */

/* Define if support Latin 4 charset */
/* #undef _LATIN4_SUPPORT */

/* Define if support Latin 5 charset */
/* #undef _LATIN5_SUPPORT */

/* Define if support Latin 6 charset */
/* #undef _LATIN6_SUPPORT */

/* Define if support Latin 7 charset */
/* #undef _LATIN7_SUPPORT */

/* Define if support Latin 8 charset */
/* #undef _LATIN8_SUPPORT */

/* Define if support Latin 9 charset */
/* #undef _LATIN9_SUPPORT */

/* Define if support LBM bmp file format */
/* #undef _LBM_FILE_SUPPORT */

/* Define if include LibGGI engine */
/* #undef _LIBGGI */

/* Define if include vcongui support */
/* #undef _LIB_VCONGUI */

/* Define if build lite version of MiniGUI */
/* #undef _LITE_VERSION */

/* Define if include IAL engine for uClinux touch screen palm/mc68ez328 */
/* #undef _MC68X328_IAL */

/* Define if include About MiniGUI Dialog Box */
/* #undef _MISC_ABOUTDLG */

/* Define if include code for screenshots */
/* #undef _MISC_SAVESCREEN */

/* Define if we can move window by mouse */
/* #undef _MOVE_WINDOW_BY_MOUSE */

/* Define if include input engine for MPC823 */
/* #undef _MPC823_IAL */

/* Define if include MS3 mouse subdriver */
#define _MS3_SUPPORT 1

/* Define if include messages' string names */
/* #undef _MSG_STRING */

/* Define if include MS mouse subdriver */
#define _MS_SUPPORT 1

/* Define if support native graphics engine on eCos LCD */
/* #undef _NATIVE_GAL_ECOSLCD */

/* Define if include native graphics engine */
/* #undef _NATIVE_GAL_ENGINE */

/* Define if support native graphics engine on FBCON */
#define _NATIVE_GAL_FBCON 1

/* Define if support native graphics engine on QVFB */
#define _NATIVE_GAL_QVFB 1

/* Define if support native graphics engine on uC/OS-II LCD */
/* #undef _NATIVE_GAL_UCOS2LCD */

/* Define if include native input engine */
/* #undef _NATIVE_IAL_ENGINE */

/* Define if include input engine for OKWAP Palm2 */
/* #undef _PALMII_IAL */

/* Define if window style is PC 3D */
#define _PC3D_WINDOW_STYLE 1

/* Define if support PCX bmp file format */
/* #undef _PCX_FILE_SUPPORT */

/* Define if window style is phone */
/* #undef _PHONE_WINDOW_STYLE_ */

/* Define if support PNG bmp file format */
/* #undef _PNG_FILE_SUPPORT */

/* Define if include PS2 mouse subdriver */
#define _PS2_SUPPORT 1

/* Define if include input engine for PX255B */
/* #undef _PX255B_IAL */

/* Define if support QPF font */
/* #undef _QPF_SUPPORT */

/* Define if include the QVFB IAL engine */
/* #undef _QVFB_IAL */

/* Define if support raw bitmap fonts */
#define _RBF_SUPPORT 1

/* Define to 0 if use clockwise rotation of screen, otherwise to 1 */
/* #undef _ROT_DIR_CW */

/* Define if include SaveBitmap function */
/* #undef _SAVE_BITMAP */

/* Define if support SHIFTJIS charset */
/* #undef _SHIFTJIS_SUPPORT */

/* Define if include IAL engine for smdk2410 touch screen */
/* #undef _SMDK2410_IAL */

/* Define if build stand-alone version of MiniGUI-Lite */
/* #undef _STAND_ALONE */

/* Define if include SVGALib engine */
/* #undef _SVGALIB */

/* Define if include IAL engine for MT T800 */
/* #undef _T800_IAL */

/* Define if include IAL engine for Tongfang STB */
/* #undef _TFSTB_IAL */

/* Define if support TGA bmp file format */
/* #undef _TGA_FILE_SUPPORT */

/* Define if support Thai charset */
/* #undef _THAI_SUPPORT */

/* Define if include input engine for THOR */
/* #undef _THOR_IAL */

/* Define if the unit of timer is 10ms */
#define _TIMER_UNIT_10MS 1

/* Define if it is tiny screen */
/* #undef _TINY_SCREEN */

/* Define if trace message dispatching of MiniGUI */
/* #undef _TRACE_MSG */

/* Define if support TrueType font based on FreeType 1.3 or FreeType 2 */
/* #undef _TTF_SUPPORT */

/* Define if support Adobe Type1 fonts */
/* #undef _TYPE1_SUPPORT */

/* Define if include input engine for UCB1X00 */
/* #undef _UCB1X00_IAL */

/* Define if include the ucos2 IAL engine */
#define _UCOSII_IAL 1

/* Define if support UNICODE */
/* #undef _UNICODE_SUPPORT */

/* Define if use new GAL interfaces */
#define _USE_NEWGAL 1

/* Define if use own implementation of malloc functions */
#define _USE_OWN_MALLOC 1

/* Define if use own implementation of stdio functions */
#define _USE_OWN_STDIO 1

/* Define if support var bitmap fonts */
#define _VBF_SUPPORT 1

/* Define if include VGA 16-color graphics engine */
/* #undef _VGA16_GAL */

/* Define if include input engine for NEC VR4181 */
/* #undef _VR4181_IAL */

/* Define if compile for eCos */
/* #undef __ECOS__ */

/* Define if compile for Linux */
/* #undef __LINUX__ */

/* Define if compile for non-Linux like OS */
#define __NOLINUX__ 1

/* Define if compile for uC/OS-II */
#define __UCOSII__ 1

/* Define if compile for uClinux */
/* #undef __uClinux__ */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define as `__inline' if that's what the C compiler calls it, or to nothing
   if it is not supported. */
#define inline __inline

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */
